import 'package:flutter/material.dart';
class AboutPage extends StatefulWidget {
  @override
  _AboutPageState createState() => _AboutPageState();
}

class _AboutPageState extends State<AboutPage> {

  static var _txtCustomHead = TextStyle(
    color: Colors.black54,
    fontSize: 17.0,
    fontWeight: FontWeight.w600,
    fontFamily: "Gotik",
  );

  static var _txtCustomSub = TextStyle(
    color: Colors.black38,
    fontSize: 15.0,
    fontWeight: FontWeight.w500,
    fontFamily: "Gotik",
  );
  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        title: Text(
          "About PlusMinus",
          style: TextStyle(
              fontWeight: FontWeight.w700,
              fontSize: 15.0,
              color: Colors.black54,
              fontFamily: "Gotik"),
        ),
        centerTitle: true,
        backgroundColor: Colors.white,
        iconTheme: IconThemeData(color: Color(0xFF6991C7)),
        elevation: 0.0,
      ),
      body: SingleChildScrollView(
        child: Container(
          color: Colors.white,
          child: Column(
            children: <Widget>[
              Padding(
                padding: const EdgeInsets.all(20.0),
                child: Divider(
                  height: 0.5,
                  color: Colors.black12,
                ),
              ),
              Padding(
                padding: EdgeInsets.only(top: 10.0, left: 15.0),
                child: Row(
                  children: <Widget>[
                    Image.asset(
                      "assets/img/Logo.png",
                      height: 50.0,
                    ),
                    Padding(
                      padding: const EdgeInsets.only(left: 12.0),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: <Widget>[
                          Text(
                            "PlusMinus",
                            style: _txtCustomSub.copyWith(
                                fontWeight: FontWeight.w600),
                          ),
                          Text(
                            "Our Story",
                            style: _txtCustomSub,
                          )
                        ],
                      ),
                    ),
                  ],
                ),
              ),
              Padding(
                padding: const EdgeInsets.all(20.0),
                child: Divider(
                  height: 0.5,
                  color: Colors.black12,
                ),
              ),
              Padding(
                padding: const EdgeInsets.all(15.0),
                child: Text(
                  "As business migrates towards the Fourth Industrial Revolution, traditional book keeping and "+
                  "cash handling methods are seeking more efficient technology driven solutions than ever before.\n\n"+
                  "We, as Conceptual Agency (Pty) Ltd, have therefore derived an innovative Fin-tech tool which is a "+
                  "first of it's kind that will assist small to medium enterprises (SMMEs) and large corporations "+
                "better manage their petty cash administration issues.\n\n"+
                "The system has been designed in such a way that eliminates the physical aspect of keeping "+
                "cash on hand and encourages business to opt for more traceable solutions such the safe "+
                "keeping of banking accounts.\n\n"+
                "Therefore our technological solution along with this proposed method of cash handling by "+
                "encouraging businesses to open banking accounts that are reserved for petty cash expenditure "+
                  "will assist businesses with administrating and producing better financial record keeping. The "+
                  "output of reports generated by PlusMinus are intended to be compatible with existing "+
                  "accounting software that accountants are currently using, auditors can thus receive data that "+
                  "could provide better audit opinions regarding the usage of petty cash in your business.\n\n"+
                  "Our story, aims to inspire businesses to adopt PlusMinus and utilize this tool to acquire "+
                  "financial education as well as use it's technology to generate more accurate financial records "+
                  "with traceable supporting documents linked to income and expenditure.",
                  style: _txtCustomSub,
                  textAlign: TextAlign.left,
                ),
              )
            ],
          ),
        ),
      ),
    );
  }
}
